networks:
  net:
    driver: bridge

services:

  web:
    build: ./website
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - net

  cloudflared:
    image: "cloudflare/cloudflared:latest"
    restart: unless-stopped
    command:
      - tunnel
      - run
      - --token
      - ${TOKEN}
    depends_on:
      - nginx
    networks:
      - net

  nginx:
    image: "nginx:latest"
    restart: unless-stopped
    expose:
      - 443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web
    networks:
      - net